### ISSUE TITLE
Readme: environment activation missing before installing in environment

### ISSUE THREAD

**Issue by spfRechenknecht** [SPF-OST/optihood#66]
Some of our users are very new to python environments.
Leaving out a step will lead to unnecessary frustration when first encountering this package.

![image](https://github.com/SPF-OST/optihood/assets/97296057/f4e165da-0d0a-49b4-b0b2-1115738f97a3)

The missing step
venv\Scripts\activate

**Comment by nehadimri1991** [comment]
Thanks, this was updated on readthedocs documentation but missing in the readme.md.
