### ISSUE TITLE
BUG: configuration file example is broken

### ISSUE THREAD

**Issue by ahobeost** [SPF-OST/optihood#78]
The example for the configuration file is no longer complete.
Some changes to the `EnergyNetwork` have broken the example.

I think `mergeBuses` is a required argument to `setFromExcel`.
When it stays `None`, the following error is raised:
![image](https://github.com/SPF-OST/optihood/assets/122869062/6a9306b6-dfb1-4652-80f7-e1c69972c281)

https://github.com/SPF-OST/optihood/blob/main/optihood/buildings.py line 108.

**Comment by nehadimri1991** [comment]
`mergebuses` is a required argument, if you set `mergeLinkBuses` to `True`. It's a list specifying the names of buses to be merged. In this case I would set it to `["electricity", "space_heat", "domestic_hot_water"]`.
